version: '1.0'

services:
    database:
        image: postgres:12.2-alpine
    student:
        source: student
        external: yes
    income:
        source: income
        external: yes
    ui-app:
        source: ui-app
        external: yes
        root_url: yes